In [ ]:
options=[
        {'label': 'New York City', 'value': 'NYC'},
        {'label': 'Montréal', 'value': 'MTL'},
        {'label': 'San Francisco', 'value': 'SF'}
]

In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import pandas as pd
import altair as alt
import vega_datasets

options=[
        {'label': 'New York City', 'value': 'NYC'},
        {'label': 'Montréal', 'value': 'MTL'},
        {'label': 'San Francisco', 'value': 'SF'}

In [3]:
df = pd.read_csv("data/clean_comparison_chart_data.csv")

In [4]:
df.head()

   Unnamed: 0  countryname     child  country_num  year       EMI
0           0  Afghanistan       all          4.0  1940       NaN
1           1  Afghanistan  daughter          4.0  1940       NaN
2           2  Afghanistan       son          4.0  1940       NaN
3           3      Albania       all          8.0  1940  0.406803
4           4      Albania  daughter          8.0  1940  0.444409

In [5]:
country_unique = df["countryname"].unique()

In [6]:
for index in range(0, len(country_unique)): 
    print("{" + f"'label': '{country_unique[index]}', 'value': '{country_unique[index]}'" + "},")
    print("")

{'label': 'Afghanistan', 'value': 'Afghanistan'},

{'label': 'Albania', 'value': 'Albania'},

{'label': 'Angola', 'value': 'Angola'},

{'label': 'Argentina', 'value': 'Argentina'},

{'label': 'Armenia', 'value': 'Armenia'},

{'label': 'Australia', 'value': 'Australia'},

{'label': 'Austria', 'value': 'Austria'},

{'label': 'Azerbaijan', 'value': 'Azerbaijan'},

{'label': 'Bangladesh', 'value': 'Bangladesh'},

{'label': 'Belarus', 'value': 'Belarus'},

{'label': 'Belgium', 'value': 'Belgium'},

{'label': 'Benin', 'value': 'Benin'},

{'label': 'Bhutan', 'value': 'Bhutan'},

{'label': 'Bolivia', 'value': 'Bolivia'},

{'label': 'Bosnia and Herzegovina', 'value': 'Bosnia and Herzegovina'},

{'label': 'Botswana', 'value': 'Botswana'},

{'label': 'Brazil', 'value': 'Brazil'},

{'label': 'Bulgaria', 'value': 'Bulgaria'},

{'label': 'Burkina Faso', 'value': 'Burkina Faso'},

{'label': 'Cabo Verde', 'value': 'Cabo Verde'},

{'label': 'Cambodia', 'value': 'Cambodia'},

{'label': 'Cameroon', 'value': 'Cameroon'},

{'label': 'Canada', 'value': 'Canada'},

{'label': 'Central African Republic', 'value': 'Central African Republic'},

{'label': 'Chad', 'value': 'Chad'},

{'label': 'Chile', 'value': 'Chile'},

{'label': 'China', 'value': 'China'},

{'label': 'Colombia', 'value': 'Colombia'},

{'label': 'Comoros', 'value': 'Comoros'},

{'label': 'Congo, Dem. Rep.', 'value': 'Congo, Dem. Rep.'},

{'label': 'Congo, Rep.', 'value': 'Congo, Rep.'},

{'label': 'Costa Rica', 'value': 'Costa Rica'},

{'label': 'Cote d'Ivoire', 'value': 'Cote d'Ivoire'},

{'label': 'Croatia', 'value': 'Croatia'},

{'label': 'Cyprus', 'value': 'Cyprus'},

{'label': 'Czech Republic', 'value': 'Czech Republic'},

{'label': 'Denmark', 'value': 'Denmark'},

{'label': 'Djibouti', 'value': 'Djibouti'},

{'label': 'Dominican Republic', 'value': 'Dominican Republic'},

{'label': 'Ecuador', 'value': 'Ecuador'},

{'label': 'Egypt, Arab Rep.', 'value': 'Egypt, Arab Rep.'},

{'label': 'El Salvador', 'value': 'El Salvador'},

{'label': 'Estonia', 'value': 'Estonia'},

{'label': 'Ethiopia', 'value': 'Ethiopia'},

{'label': 'Fiji', 'value': 'Fiji'},

{'label': 'Finland', 'value': 'Finland'},

{'label': 'France', 'value': 'France'},

{'label': 'Gabon', 'value': 'Gabon'},

{'label': 'Georgia', 'value': 'Georgia'},

{'label': 'Germany', 'value': 'Germany'},

{'label': 'Ghana', 'value': 'Ghana'},

{'label': 'Greece', 'value': 'Greece'},

{'label': 'Guatemala', 'value': 'Guatemala'},

{'label': 'Guinea', 'value': 'Guinea'},

{'label': 'Guinea-Bissau', 'value': 'Guinea-Bissau'},

{'label': 'Honduras', 'value': 'Honduras'},

{'label': 'Hungary', 'value': 'Hungary'},

{'label': 'Iceland', 'value': 'Iceland'},

{'label': 'India', 'value': 'India'},

{'label': 'Indonesia', 'value': 'Indonesia'},

{'label': 'Iran, Islamic Rep.', 'value': 'Iran, Islamic Rep.'},

{'label': 'Iraq', 'value': 'Iraq'},

{'label': 'Ireland', 'value': 'Ireland'},

{'label': 'Israel', 'value': 'Israel'},

{'label': 'Italy', 'value': 'Italy'},

{'label': 'Japan', 'value': 'Japan'},

{'label': 'Jordan', 'value': 'Jordan'},

{'label': 'Kazakhstan', 'value': 'Kazakhstan'},

{'label': 'Kenya', 'value': 'Kenya'},

{'label': 'Kiribati', 'value': 'Kiribati'},

{'label': 'Korea, Rep.', 'value': 'Korea, Rep.'},

{'label': 'Kyrgyz Republic', 'value': 'Kyrgyz Republic'},

{'label': 'Lao PDR', 'value': 'Lao PDR'},

{'label': 'Latvia', 'value': 'Latvia'},

{'label': 'Lebanon', 'value': 'Lebanon'},

{'label': 'Lesotho', 'value': 'Lesotho'},

{'label': 'Liberia', 'value': 'Liberia'},

{'label': 'Lithuania', 'value': 'Lithuania'},

{'label': 'Macedonia, FYR', 'value': 'Macedonia, FYR'},

{'label': 'Madagascar', 'value': 'Madagascar'},

{'label': 'Malawi', 'value': 'Malawi'},

{'label': 'Malaysia', 'value': 'Malaysia'},

{'label': 'Maldives', 'value': 'Maldives'},

{'label': 'Mali', 'value': 'Mali'},

{'label': 'Mauritania', 'value': 'Mauritania'},

{'label': 'Mauritius', 'value': 'Mauritius'},

{'label': 'Mexico', 'value': 'Mexico'},

{'label': 'Moldova', 'value': 'Moldova'},

{'label': 'Mongolia', 'value': 'Mongolia'},

{'label': 'Montenegro', 'value': 'Montenegro'},

{'label': 'Morocco', 'value': 'Morocco'},

{'label': 'Mozambique', 'value': 'Mozambique'},

{'label': 'Namibia', 'value': 'Namibia'},

{'label': 'Nepal', 'value': 'Nepal'},

{'label': 'Netherlands', 'value': 'Netherlands'},

{'label': 'New Zealand', 'value': 'New Zealand'},

{'label': 'Nicaragua', 'value': 'Nicaragua'},

{'label': 'Niger', 'value': 'Niger'},

{'label': 'Nigeria', 'value': 'Nigeria'},

{'label': 'Norway', 'value': 'Norway'},

{'label': 'Pakistan', 'value': 'Pakistan'},

{'label': 'Panama', 'value': 'Panama'},

{'label': 'Papua New Guinea', 'value': 'Papua New Guinea'},

{'label': 'Paraguay', 'value': 'Paraguay'},

{'label': 'Peru', 'value': 'Peru'},

{'label': 'Philippines', 'value': 'Philippines'},

{'label': 'Poland', 'value': 'Poland'},

{'label': 'Portugal', 'value': 'Portugal'},

{'label': 'Romania', 'value': 'Romania'},

{'label': 'Russian Federation', 'value': 'Russian Federation'},

{'label': 'Rwanda', 'value': 'Rwanda'},

{'label': 'Sao Tome and Principe', 'value': 'Sao Tome and Principe'},

{'label': 'Senegal', 'value': 'Senegal'},

{'label': 'Serbia', 'value': 'Serbia'},

{'label': 'Sierra Leone', 'value': 'Sierra Leone'},

{'label': 'Slovak Republic', 'value': 'Slovak Republic'},

{'label': 'Slovenia', 'value': 'Slovenia'},

{'label': 'South Africa', 'value': 'South Africa'},

{'label': 'South Sudan', 'value': 'South Sudan'},

{'label': 'Spain', 'value': 'Spain'},

{'label': 'Sri Lanka', 'value': 'Sri Lanka'},

{'label': 'Sudan', 'value': 'Sudan'},

{'label': 'Swaziland', 'value': 'Swaziland'},

{'label': 'Sweden', 'value': 'Sweden'},

{'label': 'Switzerland', 'value': 'Switzerland'},

{'label': 'Taiwan, China', 'value': 'Taiwan, China'},

{'label': 'Tajikistan', 'value': 'Tajikistan'},

{'label': 'Tanzania', 'value': 'Tanzania'},

{'label': 'Thailand', 'value': 'Thailand'},

{'label': 'Timor-Leste', 'value': 'Timor-Leste'},

{'label': 'Togo', 'value': 'Togo'},

{'label': 'Tonga', 'value': 'Tonga'},

{'label': 'Tunisia', 'value': 'Tunisia'},

{'label': 'Turkey', 'value': 'Turkey'},

{'label': 'Tuvalu', 'value': 'Tuvalu'},

{'label': 'Uganda', 'value': 'Uganda'},

{'label': 'Ukraine', 'value': 'Ukraine'},

{'label': 'United Kingdom', 'value': 'United Kingdom'},

{'label': 'United States', 'value': 'United States'},

{'label': 'Uruguay', 'value': 'Uruguay'},

{'label': 'Uzbekistan', 'value': 'Uzbekistan'},

{'label': 'Vanuatu', 'value': 'Vanuatu'},

{'label': 'Venezuela, RB', 'value': 'Venezuela, RB'},

{'label': 'Vietnam', 'value': 'Vietnam'},

{'label': 'West Bank and Gaza', 'value': 'West Bank and Gaza'},

{'label': 'Yemen, Rep.', 'value': 'Yemen, Rep.'},

{'label': 'Zambia', 'value': 'Zambia'},

{'label': 'Africa', 'value': 'Africa'},

{'label': 'Asia', 'value': 'Asia'},

{'label': 'Europe', 'value': 'Europe'},

{'label': 'North America', 'value': 'North America'},

{'label': 'Oceania', 'value': 'Oceania'},

{'label': 'South America', 'value': 'South America'},

{'label': 'Developing economies', 'value': 'Developing economies'},

{'label': 'High-income economies', 'value': 'High-income economies'},